version: "3.8"
services:
  frontend:
    build: ./app # Chemin vers le dossier du frontend Angular
    ports:
      - "4200:80" # Expose le port 80 pour NGINX (frontend Angular)
    depends_on:
      - backend
    networks:
      - database

  backend:
    container_name: backend
    build: ./api # Chemin vers le dossier du backend Node.js
    ports:
      - "3000:3000" # Expose le port du backend
    depends_on:
      - database
    env_file: 
      - "./api/.env"
    networks:
      - database

  database:
    image: mysql:8.0 # Image MySQL
    container_name: mysql_database
    env_file: 
      - "./db/.env"
    ports:
      - "3306:3306" # Expose le port MySQL
    volumes:
      - mysql_data:/var/lib/mysql
      - ./db:/docker-entrypoint-initdb.d
    networks:
      - database

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin:4.9
    ports:
      - 8080:80
    env_file: 
      - "./phpmyadmin/.env"
    networks:
      - database 

volumes:
  mysql_data:
networks:
  database:
